### ISSUE TITLE
TypeError during reflection for index metadata

### ISSUE THREAD

**Issue by hab6** [ActianCorp/sqlalchemy-ingres#29]
### Description
**Given:** Using the SQLAlchemy Ingres connector with Superset.
From the Superset UI, using the **SQL Lab** page and selecting `SEE TABLE SCHEMA` for a chosen database schema causes error `TypeError: 'tuple' object is not callable`

### Environment
Ubuntu 22.04.2 LTS
Superset  3.1.0
SQLAlchemy                1.4.51
sqlalchemy-ingres         0.0.4

### Full Stack Dump
    2024-02-13 18:21:49,949:ERROR:flask_appbuilder.api:'tuple' object is not callable
    Traceback (most recent call last):
      File "/home/ss/.venv/lib/python3.10/site-packages/flask_appbuilder/api/__init__.py", line 110, in wraps
        return f(self, *args, **kwargs)
      File "/home/ss/.venv/lib/python3.10/site-packages/superset/views/base_api.py", line 127, in wraps
        raise ex
      File "/home/ss/.venv/lib/python3.10/site-packages/superset/views/base_api.py", line 121, in wraps
        duration, response = time_function(f, self, *args, **kwargs)
      File "/home/ss/.venv/lib/python3.10/site-packages/superset/utils/core.py", line 1454, in time_function
        response = func(*args, **kwargs)
      File "/home/ss/.venv/lib/python3.10/site-packages/superset/utils/log.py", line 255, in wrapper
        value = f(*args, **kwargs)
      File "/home/ss/.venv/lib/python3.10/site-packages/superset/databases/api.py", line 740, in table_metadata
        table_info = get_table_metadata(database, table_name, schema_name)
      File "/home/ss/.venv/lib/python3.10/site-packages/superset/databases/utils.py", line 74, in get_table_metadata
        indexes = get_indexes_metadata(database, table_name, schema_name)
      File "/home/ss/.venv/lib/python3.10/site-packages/superset/databases/utils.py", line 39, in get_indexes_metadata
        indexes = database.get_indexes(table_name, schema_name)
      File "/home/ss/.venv/lib/python3.10/site-packages/superset/models/core.py", line 863, in get_indexes
        return self.db_engine_spec.get_indexes(self, inspector, table_name, schema)
      File "/home/ss/.venv/lib/python3.10/site-packages/superset/db_engine_specs/base.py", line 1298, in get_indexes
        return inspector.get_indexes(table_name, schema)
      File "/home/ss/.venv/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 605, in get_indexes
        return self.dialect.get_indexes(
      File "<string>", line 2, in get_indexes
      File "/home/ss/.venv/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
        ret = fn(self, con, *args, **kw)
      File "/home/ss/.venv/lib/python3.10/site-packages/sqlalchemy_ingres/base.py", line 599, in get_indexes
        params(*params, self.denormalize_name(schema))
    TypeError: 'tuple' object is not callable

### SQLAlchemy Version Requirement
_(Not sure whether this is relevant, although it could be, so is worth documenting)_  

Both **Apache Superset** and **Flask-AppBuilder** require a pre-2.x version of SQLAlchemy. If attempting to install a 2.x version of SQLAlchemy alongside these packages, the following error occurs.

    $ python -m pip install sqlalchemy==2.0.27
    Collecting sqlalchemy==2.0.27
    ...
    ERROR: pip's dependency resolver does not currently take into account all the packages
    that are installed. This behaviour is the source of the following dependency conflicts.
    flask-appbuilder 4.3.10 requires SQLAlchemy<1.5, but you have sqlalchemy 2.0.27
    which is incompatible.
    apache-superset 3.1.0 requires sqlalchemy<2,>=1.4, but you have sqlalchemy 2.0.27
    which is incompatible.

### Potential Related Issues
#22 Issue for reflection error with meta data lookup
#23 Pull request containing parameter type changes

**Comment by hab6** [comment]
Simple test to reproduce the error: `TypeError: 'tuple' object is not callable`

    import os
    import sys
    import sqlalchemy
    import sqlalchemy_ingres

    print('Python %s on %s' % (sys.version, sys.platform))
    print('SQLAlchemy %r' % sqlalchemy.__version__)

    driver_name = os.environ.get('SQLALCHEMY_INGRES_ODBC_DRIVER_NAME') or 'Actian'
    print('SQLALCHEMY_INGRES_ODBC_DRIVER_NAME %r' % driver_name)

    con_str = os.environ['DATABASE_URI']

    engine = sqlalchemy.create_engine(con_str)

    schema = "actian"
    table_name = "demotable"
    inspector = sqlalchemy.inspect(engine)
    inspector.get_indexes(table_name=table_name, schema=schema)

    metadata = sqlalchemy.MetaData()
    view_support = False

    metadata.reflect(
                views=view_support,
                bind=engine,
                schema=schema,
            )

**Comment by hab6** [comment]
Opened PR #33 with fix

**Comment by hab6** [comment]
The same bug was present in functions `get_indexes` and `get_view_definition` of [base.py](https://github.com/ActianCorp/sqlalchemy-ingres/blob/master/lib/sqlalchemy_ingres/base.py) with a fix in PR #33.

**Comment by clach04** [comment]
@hab6 looks like commits in https://github.com/ActianCorp/sqlalchemy-ingres/pull/33/commits didn't mention this issue number so it's not been auto closed. Is this closable now?

**Comment by hab6** [comment]
@clach04 Yes, this can be closed. My bad on not mentioning this issue in the commits for #33
