### ISSUE TITLE
Updates needed to work with SQLAlchemy 2.0

### ISSUE THREAD

**Issue by hab6** [ActianCorp/sqlalchemy-ingres#5]
The current Ingres Dialect code is built to work with SQLAlchemy (SA) version 1.x. Attempting to use the dialect code with SA 2.0 (currently in beta) will generate errors. The dialect code needs to be updated (forked) to work with SQLAlchemy version 2.0.

**Comment by clach04** [comment]
Thanks @hab6 if you have some sample errors/failures/trace-backs it would be useful to get those included in the report.

Definitely worth a PR to note in the readme that the (in-progress/forth-coming) SA 2.x version is known to NOT work (and impacts the recommended pip install instructions).

**Comment by hab6** [comment]
### Error and stack output with simple test program using Ingres dialect `0.3` with SA `2.0.0b1`

#### Platform
```
λ uname -a
MSYS_NT-10.0-19042 xxxxxxxx 3.3.6-341.x86_64 2022-09-05 20:28 UTC x86_64 Msys
```

#### Installed versions
```
λ python --version
Python 3.10.7     
```
```
λ pip show ingres-sa-dialect
Name: ingres-sa-dialect
Version: 0.3
Summary: An Ingres dialect for SQLAlchemy
Home-page:
Author: Chris Clark
Author-email: Chris.Clark@actian.com
License: MIT
Location: c:\users\mhabiger\data\github\ingres_sa_dialect\lib
Requires:
Required-by:
```
```
λ pip show sqlalchemy
Name: SQLAlchemy
Version: 2.0.0b1
Summary: Database Abstraction Library
Home-page: https://www.sqlalchemy.org
Author: Mike Bayer
Author-email: mike_mp@zzzcomputing.com
License: MIT
Location: c:\users\mhabiger\appdata\local\programs\python\python310\lib\site-packages
Requires: greenlet, typing-extensions
Required-by:
```

#### Test program
```
λ cat 2test.py
import sys
import sqlalchemy
import ingres_sa_dialect

print('Python %s on %s' % (sys.version, sys.platform))
print(sqlalchemy.__version__)
con_str = 'ingres:///demodb'  # local demodb
print(con_str)
print(ingres_sa_dialect.base.dialect().create_connect_args(url=sqlalchemy.engine.make_url(con_str)))

engine = sqlalchemy.create_engine(con_str)
connection = engine.connect()
query = 'SELECT * FROM iidbconstants'
for row in connection.execute(sqlalchemy.text(query)):
        print(row)
```


#### Test output
```
λ python 2test.py
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] on win32                               
2.0.0b1                                                                                                                        
ingres:///demodb                                                                                                               
(['Driver={Actian II};Database=demodb;Server=(local)'], {})                                                                    
C:\Users\mhabiger\Data\test\python\saTest\2test.py:11: SADeprecationWarning: The dbapi() classmethod on dialect classes has bee
n renamed to import_dbapi().  Implement an import_dbapi() classmethod directly on class <class 'ingres_sa_dialect.pyodbc.Ingres
_pyodbc'> to remove this warning; the old .dbapi() classmethod may be maintained for backwards compatibility.                  
  engine = sqlalchemy.create_engine(con_str)                                                                                   
Traceback (most recent call last):                                                                                             
  File "C:\Users\mhabiger\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 1388, in e
xecute                                                                                                                         
    meth = statement._execute_on_connection                                                                                    
AttributeError: 'str' object has no attribute '_execute_on_connection'                                                         
                                                                                                                               
The above exception was the direct cause of the following exception:                                                           
                                                                                                                               
Traceback (most recent call last):                                                                                             
  File "C:\Users\mhabiger\Data\test\python\saTest\2test.py", line 12, in <module>                                              
    connection = engine.connect()                                                                                              
  File "C:\Users\mhabiger\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 3210, in c
onnect                                                                                                                         
    return self._connection_cls(self)                                                                                          
  File "C:\Users\mhabiger\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 147, in __
init__                                                                                                                         
    self._dbapi_connection = engine.raw_connection()                                                                           
  File "C:\Users\mhabiger\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 3234, in r
aw_connection                                                                                                                  
    return self.pool.connect()                                                                                                 
  File "C:\Users\mhabiger\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\pool\base.py", line 397, in conn
ect                                                                                                                            
    return _ConnectionFairy._checkout(self)                                                                                    
  File "C:\Users\mhabiger\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\pool\base.py", line 1193, in _ch
eckout                                                                                                                         
    fairy = _ConnectionRecord.checkout(pool)                                                                                   
  File "C:\Users\mhabiger\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\pool\base.py", line 660, in chec
kout                                                                                                                           
    rec = pool._do_get()                                                                                                       
  File "C:\Users\mhabiger\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\pool\impl.py", line 168, in _do_
get                                                                                                                            
    with util.safe_reraise():                                                                                                  
  File "C:\Users\mhabiger\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\util\langhelpers.py", line 148, 
in __exit__                                                                                                                    
    raise exc_value.with_traceback(exc_tb)                                                                                     
  File "C:\Users\mhabiger\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\pool\impl.py", line 166, in _do_
get                                                                                                                            
    return self._create_connection()                                                                                           
  File "C:\Users\mhabiger\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\pool\base.py", line 338, in _cre
ate_connection                                                                                                                 
    return _ConnectionRecord(self)                                                                                             
  File "C:\Users\mhabiger\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\pool\base.py", line 623, in __in
it__                                                                                                                           
    self.__connect()                                                                                                           
  File "C:\Users\mhabiger\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\pool\base.py", line 856, in __co
nnect                                                                                                                          
    )._exec_w_sync_on_first_run(self.dbapi_connection, self)                                                                   
  File "C:\Users\mhabiger\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\event\attr.py", line 473, in _ex
ec_w_sync_on_first_run                                                                                                         
    self(*args, **kw)                                                                                                          
  File "C:\Users\mhabiger\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\event\attr.py", line 487, in __c
all__                                                                                                                          
    fn(*args, **kw)                                                                                                            
  File "C:\Users\mhabiger\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\util\langhelpers.py", line 1868,
 in go                                                                                                                         
    return once_fn(*arg, **kw)                                                                                                 
  File "C:\Users\mhabiger\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\create.py", line 746, in 
first_connect                                                                                                                  
    dialect.initialize(c)                                                                                                      
  File "C:\Users\mhabiger\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\default.py", line 481, in
 initialize                                                                                                                    
    self.default_schema_name = self._get_default_schema_name(                                                                  
  File "c:\users\mhabiger\data\github\ingres_sa_dialect\lib\ingres_sa_dialect\base.py", line 693, in get_default_schema_name   
    rs = connection.execute(sqltext)                                                                                           
  File "C:\Users\mhabiger\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 1390, in e
xecute                                                                                                                         
    raise exc.ObjectNotExecutableError(statement) from err                                                                     
sqlalchemy.exc.ObjectNotExecutableError: Not an executable object: "SELECT dbmsinfo('username')"                               
```

**Comment by hab6** [comment]
One clarification about the pip install. For now, it appears that any of the following commands will install the latest **pre-2.0** release (e.g. `1.4.41`).

```
pip install sqlalchemy
python -m pip install sqlalchemy
python -m pip install sqlalchemy==1.4.41
```

I had trouble earlier with SA `2.0.0b1` (see above errors/stack) and later concluded that I had specifically downloaded and installed version `2.0.0b1` from https://pypi.org/project/SQLAlchemy/2.0.0b1/.  After removing this beta version and installing SA version `1.4.41`, my test program worked.

**Comment by clach04** [comment]
Thanks @hab6 , great notes!

One comment/suggestion on version pinning:

> One clarification about the pip install. For now, it appears that any of the following commands will install the latest **pre-2.0** release (e.g. `1.4.41`).
> 
> ```
> pip install sqlalchemy
> python -m pip install sqlalchemy
> python -m pip install sqlalchemy==1.4.41
> ```
> 
> I had trouble earlier with SA `2.0.0b1` (see above errors/stack) and later concluded that I had specifically downloaded and installed version `2.0.0b1` from https://pypi.org/project/SQLAlchemy/2.0.0b1/. After removing this beta version and installing SA version `1.4.41`, my test program worked.

Today pip will work, once 2.0 is published the first two pip install directives will cause a problem, recommend instead:
        
        pip install 'sqlalchemy < 2.0.0'
        python -m pip install 'sqlalchemy < 2.0.0'
        python -m pip install sqlalchemy==1.4.41

**Comment by hab6** [comment]
PR https://github.com/ActianCorp/ingres_sa_dialect/pull/18 added support for SQLAlchemy v2 with backward compatibility for SA v1.

**Comment by clach04** [comment]
If we think this is ready readme update is needed:

https://github.com/ActianCorp/ingres_sa_dialect/blob/master/README.md?plain=1#L14

**Comment by hab6** [comment]
Recent testing has included running the SQLAlchemy test suite with the latest SQLAlchemy-Ingres dialect code and the latest versions 1.4.x and 2.0.x of SQLAlchemy. Test results are documented in internal ticket **II-10985**.

Plan is to close this issue (#5) once PR #38 is merged.
